name: {{ cookiecutter.conda_environment_name }}

channels:
  - esri
  - conda-forge

dependencies:
  # - anaconda  # useful if building conda packages, but REALLY heavy install
  - arcgis==1.8.2
  - cookiecutter
  - dask
  - h3-py
  - jupyterlab
  - mkdocs
  - pip
  - progress
  - pylint
  - pytest
  - python-dotenv
  - pyyaml
  - scipy
  - scikit-learn
  - seaborn
  - shapely
  - swifter
  - tabulate
  - tqdm
  - pip:
    - azure-storage-blob
    - bump2version
    - ipykernel
    - pyarrow
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx_rtd_theme
    - twine
